version: '3'
services:
  db:
    build:
      context: ./mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    image: 'jayshamnani/mysql:1.0'
    ports:
      - '3306:3306'
    restart: unless-stopped

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    depends_on:
      - db
    image: 'jayshamnani/wordpress:1.0'
    links:
      - db
    restart: always

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - wordpress
    image: 'jayshamnani/nginx:1.0'
    links:
      - wordpress
    ports:
      - '80:80'
    restart: unless-stopped
    extra_hosts:
      - "example.com:127.0.0.1"